spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
